apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-node-selector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: main-container
          image: nginx:latest
      nodeSelector:
        special-node: "true"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
