apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-init-container
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: main-container
          image: nginx:latest
      initContainers:
        - name: init-container
          image: busybox:latest
          command: ['sh', '-c', 'echo "Init Container is running before main container"']
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
