apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota
  namespace: nginx
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
